### ISSUE TITLE
Failed to load config "@ljharb" 

### ISSUE THREAD

**Issue by Clevinpro** [ljharb/call-bind#3]
<img width="948" alt="Screenshot 2021-04-14 at 18 52 53" src="https://user-images.githubusercontent.com/14553895/114740847-e59bbc80-9d52-11eb-8032-011457242b18.png">

Failed after: **react-scripts start**

**Comment by ljharb** [comment]
This happens if you try to lint files in node_modules, which doesn’t make any sense. Presumably this isn’t a stock CRA app; you’ve modified something about the eslint config?

**Comment by Clevinpro** [comment]
no, I have several package.json 
like /root and root/src/ui - for using storybook inside.
It happens after I installed dependency for storybook, If delete node_modules from root/src/ui, it works correctly

**Comment by ljharb** [comment]
If you have nested package.jsons (and thus nested node_modules), then you always have to add a root `.eslintignore` that ignores `**/node_modules/**`. That will resolve this issue.
