### ISSUE TITLE
Latest versions have "Cannot find module 'define-data-property'"

### ISSUE THREAD

**Issue by patricktyndall** [ljharb/call-bind#5]
Hi, I believe today's releases have broken compatibility. I can't `require` version 1.04 (I get `Cannot find module 'define-data-property'`)

I believe this is due to an update to the `set-function-length` dep version -- the new version of `set-function-length` has [moved `define-data-property` into devDependencies](https://github.com/ljharb/set-function-length/commit/d727e7c6c9a40d7bf26797694e500ea68741feea)

I'm finding this as a Serverless SDK user.

TIA

**Comment by ljharb** [comment]
Already fixed in v1.1.1 of `set-function-length`, see https://github.com/ljharb/set-function-length/issues/2.
