### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by LewisLen** [ljharb/call-bind#6]
3: import * as _vite_plugin_require_transform_get_intrinsic_0 from "get-intrinsic";
4: var GetIntrinsic = _vite_plugin_require_transform_get_intrinsic_0.default || _vite_plugin_require_transform_get_intri...
5: import * as _vite_plugin_require_transform_./_1 from "./";
                                              ^
6: var callBind = _vite_plugin_require_transform_./_1.default || _vite_plugin_require_transform_./_1;
7: var $indexOf = callBind(GetIntrinsic('String.prototype.indexOf'));
error during build:
SyntaxError: Unexpected token (5:43) /xxx/x/node_modules/call-bind/callBound.js

**Comment by ljharb** [comment]
I’m not sure what the issue is here, but if you have trouble when using vite, file an issue with vite. In particular, there can’t be a slash or a dot in an “as” identifier.
